export default ImagesPath = {
    logo : require("../images/harHathKalam.png"),
    fb : require("../images/fb.png"),
    twitter : require("../images/twitter.png"),
    insta : require("../images/insta.png"),
    youtube : require("../images/youtube.png"),
    slide1 : require("../images/values1.png"),
    slide2 : require("../images/kalam.jpeg"),
    slide3 : require("../images/kalam2.jpeg"),
    slide4 : require("../images/harhath.jpeg"),
    slide5 : require("../images/harhathkalam2.jpeg"),
    people : require("../images/people.png"),
    feet : require("../images/feet.png"),
    self : require("../images/self.png"),
    salute : require("../images/salute.png"),
    arrow : require("../images/arrow.png"),
    story1 : require("../images/story1.webp"),
    story2 : require("../images/story2.webp"),
    story3 : require("../images/story3.webp"),
    literacy : require("../images/literacy.jpeg"),
    community : require("../images/community.jpeg"),
    safespace : require("../images/safespace.jpeg"),
    women : require("../images/women.jpeg"),
    address: require("../images/address.png"),
    dev: require("../images/dev.png"),
    sharadha: require("../images/shradha.png"),
    mehul: require("../images/mehul.png"),
     riya: require("../images/Riya.jpeg"),
     shaila: require("../images/Shailaja.png"),
    charu : require("../images/Charu.png"),
    arvind : require("../images/Arwinder.png"),  

}